version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  soss-v2-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soss-v2
    depends_on:
      - postgres
    ports:
      - "8000:8000"

volumes:
  postgres-data:
